### ISSUE TITLE
Feature request: content type for agent messages

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/xmtp-ai#109]
### Is your feature request related to a problem?

Other clients have no way of knowing whether a message was sent by a human or an agent.

### Describe the solution to the problem

Use TextEncoder() with a new `agent-message` ContentTypeId for all generated messages. This is not a trustless solution.

e.g.

```
import {
  ContentTypeId,
  ContentCodec,
  EncodedContent,
} from "@xmtp/content-type-primitives";

export const ContentTypeAgentMessage = new ContentTypeId({
  authorityId: "xmtp.org",
  typeId: "agent-message",
  versionMajor: 1,
  versionMinor: 0,
});

export class AgentMessageCodec implements ContentCodec<string> {
  contentType = ContentTypeAgentMessage;

  encode(content: string): EncodedContent {
    return {
      type: this.contentType,
      parameters: {},
      content: new TextEncoder().encode(content),
      fallback: content,
    };
  }

  decode(encodedContent: EncodedContent): string {
    return new TextDecoder().decode(encodedContent.content);
  }

  fallback(content: string): string | undefined {
    return content;
  }

  shouldPush(): boolean {
    return true;
  }
}
```

### Describe the uses cases for the feature

A client like Converse may wish to display messages differently if they are known to be agents.

An agent may want to handle agent-generated messages differently from messages assumed to be from humans. For instance, an agent may wish to ignore other agents to prevent loops.

**Comment by humanagent** [comment]
# Agent Message Content Type

The AgentMessage content type allows XMTP agents to send messages with hidden metadata while maintaining compatibility with regular clients.

## Structure

```typescript
class AgentMessage {
  text: string;      // Visible message content
  metadata: {
    agentId: string;
    skillUsed?: string; 
    timestamp: number;
    isAutomated: boolean;
    [key: string]: any; // Additional custom metadata
  }
}
```

## Usage

### Basic Message

```typescript
await context.sendAgentMessage("Hello!", {
  agentId: "support-bot"
});
```

### Message with Skill Info

```typescript
await context.sendAgentMessage("The domain is available!", {
  agentId: "ens-bot",
  skillUsed: "check-domain",
  domainChecked: "fabri.eth"
});
```

- Tested in Coinbase Wallet and Converse
- Message Can be Empty
