### ISSUE TITLE
Bug: Imports only work with `.js` suffix

### ISSUE THREAD

**Issue by humanagent** [ephemeraHQ/xmtp-ai#120]
This works
`import { handler as tipping } from "./handler/tipping.js";`
This doesn't
`import { handler as tipping } from "./handler/tipping";`
`import { handler as tipping } from "./handler/tipping.ts";`

@saulmc had other examples using relative imports like `@/path/file`

**Comment by saulmc** [comment]
@fabriguespe I don't actually have this problem exactly; aliases etc work fine --

what happens is when i run a test suite, `skills` is empty in the handler context because:
- MessageKit looks for `skillsConfigPath` at `dist/{$skillsConfigPath}`
- MessageKit expects compiled Javascript for the skills file and all its imports

**Comment by rygine** [comment]
what's the context of these imports? this looks like a module resolution issue.

**Comment by fabriguespe** [comment]
Sorry, the issue @saulmc is talking about is resolving files in his tests, ill create a new one for the test relative imports that saul is mentioning.

Regarding the .js resolving, can we prevent developers to be force to use .js? @rygine

**Comment by saulmc** [comment]
I'm not forced to use .js in my project. Here's the tsconfig:

```
{
    "include": [
      "src/**/*",
      "tests/**/*"
    ],
    "exclude": [
      "node_modules"
    ],
    "compilerOptions": {
      "outDir": "./dist",
      "rootDir": ".",
      "esModuleInterop": true,
      "declaration": true,
      "declarationMap": true,
      "forceConsistentCasingInFileNames": true,
      "isolatedModules": true,
      "lib": [
        "ESNext"
      ],
      "module": "ESNext",
      "moduleResolution": "node",
      "resolveJsonModule": true,
      "skipLibCheck": true,
      "sourceMap": true,
      "strict": true,
      "target": "ESNext",
      "types": ["node", "vitest/globals"],
      "baseUrl": ".",
      "paths": {
        "@services/*": ["src/services/*"],
        "@handlers/*": ["src/handlers/*"],
        "@commandHandlers": ["src/handlers/commandHandlers"],
        "@utils/*": ["src/utils/*"],
        "@models/*": ["src/models/*"],
        "@codecs/*": ["src/codecs/*"],
        "@tests/*": ["tests/*"],
        "@skills": ["src/skills.ts"],
        "@prompts": ["src/prompts.ts"],
        "@types": ["src/types"],
      }
    },
  }
```

**Comment by humanagent** [comment]
Experimented a bit but no luck

```
{
  "extends": "@xmtp/tsconfig/base.json",
  "include": ["src/**/*"],
  "compilerOptions": {
    "outDir": "./dist",
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowImportingTsExtensions": true,
    "emitDeclarationOnly": true,
    "declaration": true,
    "declarationMap": true
  }
}
```
